import "./home.scss"

const Home = () => {
  return (
    <div>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
    </div>
  )
}

export default Home
